apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nats
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nats
    spec:
      containers:
      - name: nats
        image: quay.io/concur_platform/nats:0.9.6
        args: ["--service", "nats.default.svc.cluster.local", "-m", "8222"]
        ports:
        - containerPort: 8222
        - containerPort: 6222
        - containerPort: 4222
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP