apiVersion: v1
kind: Deployment
metadata:
  name: eve-agent
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: eve-agent
    spec:
      containers:
      - name: eve-agent-create
        image: quay.io/concur_platform/eve:c7e1de6
        args: ["eve", "agent", "create"]
      - name: eve-agent-delete
        image: quay.io/concur_platform/eve:c7e1de6
        args: ["eve", "agent", "delete"]