apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: eve-agent
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: eve-agent
    spec:
      containers:
      - name: eve-agent-create
        image: quay.io/concur_platform/eve:60c5d4b
        args: ["eve", "agent", "create"]
        volumeMounts:
        - name: eve-tls
          mountPath: /opt/eve/tls
          readOnly: true
        - name: backend-tls
          mountPath: /opt/backend/tls
          readOnly: true
        envFrom:
        - configMapRef:
            name: eve-config
        env:
        - name: EVE_RETHINK_NODES
          valueFrom:
            configMapKeyRef:
              name: rethink-cluster-config
              key: eve_rethink_nodes
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: token
      - name: eve-agent-delete
        image: quay.io/concur_platform/eve:60c5d4b
        args: ["eve", "agent", "delete"]
        volumeMounts:
        - name: eve-tls
          mountPath: /opt/eve/tls
          readOnly: true
        - name: backend-tls
          mountPath: /opt/backend/tls
          readOnly: true
        envFrom:
        - configMapRef:
            name: eve-config
        env:
        - name: EVE_RETHINK_NODES
          valueFrom:
            configMapKeyRef:
              name: rethink-cluster-config
              key: eve_rethink_nodes
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: token
      volumes:
      - name: eve-tls
        secret:
          secretName: eve-tls
      - name: backend-tls
        secret:
          secretName: backend-tls
